#!/usr/bin/env python3
"""Generate the reference catalogs from their live sources.

The generated files are ``docs/CONFIG.md`` (every setting, its environment
variable, workspace key and default, from :data:`reportal.settings.SETTINGS`),
``docs/MCP_TOOLS.md`` (every registered MCP tool and its access hint, from
``reportal.mcp_tools``) and ``docs/MODULE_MAP.md`` (every module, the
subsystem page that owns it, and its one-line purpose, from the pages'
``Sources:`` lines).

Run without arguments to rewrite the files in place.  ``--check`` compares and
exits 1 on any difference, which is how ``tests/test_generated_docs.py`` keeps
a hand edit from surviving the gate.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
SUBSYSTEMS = DOCS / "subsystems"
PACKAGE = REPO / "src" / "reportal"

GENERATED_HEADER = (
    "<!-- Generated by `scripts/gen_docs.py` from the live registries and page"
    " `Sources:` lines. Do not edit by hand: run the script and commit the"
    " result. `tests/test_generated_docs.py` fails on an uncommitted"
    " regeneration. -->\n"
)


def subsystem_sources(directory: Path = SUBSYSTEMS) -> dict[str, tuple[str, ...]]:
    """The modules each subsystem page owns, from its ``Sources:`` line.

    Maps the page's filename stem to the repository-relative module paths it
    declares, in declaration order.  A page with no ``Sources:`` line, or one
    that names a path outside ``src/reportal``, raises: the ownership claim is
    the page's contract with the module map.
    """
    owned: dict[str, tuple[str, ...]] = {}
    for page in sorted(directory.glob("*.md")):
        if page.name == "README.md":
            continue
        declared: tuple[str, ...] | None = None
        for line in page.read_text(encoding="utf-8").splitlines():
            if not line.startswith("Sources:"):
                continue
            entries = tuple(part.strip() for part in line[len("Sources:") :].split(","))
            declared = tuple(entry for entry in entries if entry)
            break
        if not declared:
            raise ValueError(f"{page.name} declares no Sources: line")
        for entry in declared:
            if not entry.startswith("src/reportal/") or not entry.endswith(".py"):
                raise ValueError(f"{page.name} claims {entry!r}, not a src/reportal module")
        owned[page.stem] = declared
    return owned


def _escape(text: str) -> str:
    """One table cell: pipes escaped, whitespace collapsed."""
    return " ".join(text.replace("|", "\\|").split())


def _first_sentence(text: str) -> str:
    """A module's purpose: the first sentence of its docstring."""
    collapsed = " ".join(text.split())
    for marker in (". ", "! ", "? "):
        head, found, _tail = collapsed.partition(marker)
        if found:
            return f"{head}{found.strip()}"
    return collapsed


def _module_purposes() -> dict[str, str]:
    """Each package module's one-line purpose, from its own docstring."""
    found: dict[str, str] = {}
    for path in sorted(PACKAGE.glob("*.py")):
        docstring = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
        found[path.name] = _first_sentence(docstring) or "No module docstring."
    return found


def render_config() -> str:
    """``docs/CONFIG.md``: every setting reportal reads."""
    from reportal import settings

    rows: dict[str, list[Any]] = {}
    for setting in settings.SETTINGS:
        rows.setdefault(setting.table or "", []).append(setting)
    lines = [
        GENERATED_HEADER,
        "# Configuration catalog\n",
        "Every setting reportal reads, in one place: the environment variable, the",
        "`reportal.toml` key, the default in force and what reads it. Resolution is",
        "first match wins (environment, then the workspace table), so a value in both",
        "places is the environment's. `reportal config` prints the same rows resolved",
        "for this workspace; `reportal doctor` reports the ones that are set wrong.",
        "",
        "A setting with no workspace key can only come from the environment or its",
        "default. A secret is listed with no default value: its value is never",
        "returned, only its presence and length.\n",
    ]
    for table in sorted(rows):
        heading = f"[{table}]" if table else "Environment only"
        lines.append(f"## {heading}\n")
        lines.append("| Setting | Environment | Workspace key | Kind | Default | What it is |")
        lines.append("|---------|-------------|---------------|------|---------|------------|")
        for setting in sorted(rows[table], key=lambda item: item.name):
            kind = "secret" if setting.secret else setting.kind
            lines.append(
                "| `{name}` | {env} | {key} | {kind} | {default} | {describe} |".format(
                    name=_escape(setting.name),
                    env=f"`{_escape(setting.env)}`" if setting.env else "",
                    key=f"`{_escape(setting.table_key)}`" if setting.table_key else "",
                    kind=_escape(kind),
                    default=f"`{_escape(setting.default)}`" if setting.default else "",
                    describe=_escape(setting.describe),
                )
            )
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_mcp_tools() -> str:
    """``docs/MCP_TOOLS.md``: every registered MCP tool."""
    from reportal import mcp_tools

    tools = mcp_tools.tools()
    read_only = [tool for tool in tools if tool.annotations.read_only_hint]
    destructive = [tool for tool in tools if not tool.annotations.read_only_hint]
    lines = [
        GENERATED_HEADER,
        "# MCP tool catalog\n",
        (
            f"The {len(tools)} tools the MCP registry exposes"
            f" ({len(read_only)} read-only, {len(destructive)} destructive)."
        ),
        "`reportal mcp` serves them over stdio JSON-RPC; `POST /mcp` and `GET /mcp`",
        "serve the same registry over HTTP. A read-only tool runs at once; a",
        "destructive tool pauses an agent run for confirmation. Names must be unique",
        "across built-ins and plugin entry points.",
        "",
        "Handlers call reportal internals directly, never back over HTTP. The",
        "registry, its registration rules and the agent loop that drives it are on",
        "[the mcp subsystem page](subsystems/mcp.md); counts are pinned by",
        "`tests/test_mcp.py`.\n",
    ]
    for title, group in (("Read-only tools", read_only), ("Destructive tools", destructive)):
        lines.append(f"## {title}\n")
        lines.append("| Tool | What it does |")
        lines.append("|------|--------------|")
        for tool in sorted(group, key=lambda item: item.name):
            lines.append(f"| `{_escape(tool.name)}` | {_escape(tool.description)} |")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_module_map() -> str:
    """``docs/MODULE_MAP.md``: every module, its owner page and its purpose."""
    purposes = _module_purposes()
    owned = subsystem_sources()
    owners: dict[str, str] = {}
    for page, modules in owned.items():
        for module in modules:
            owners[module.rsplit("/", 1)[-1]] = page
    lines = [
        GENERATED_HEADER,
        "# Module map\n",
        "Every module in `src/reportal/`, the subsystem page that owns it, and the",
        "purpose its own docstring states. The ownership column comes from each",
        "page's `Sources:` line, so a module in no page or in two fails",
        "`tests/test_docs_structure.py`.",
        "",
        "The process layout in [ARCHITECTURE.md](ARCHITECTURE.md#process-layout) is",
        "the reading order across these modules; the",
        "[subsystems index](subsystems/README.md) is the page-per-subsystem view.\n",
        "| Module | Subsystem | Purpose |",
        "|--------|-----------|---------|",
    ]
    for module in sorted(purposes):
        page = owners.get(module)
        cell = f"[{page}](subsystems/{page}.md)" if page else "**unowned**"
        lines.append(f"| `{module}` | {cell} | {_escape(purposes[module])} |")
    return "\n".join(lines).rstrip("\n") + "\n"


GENERATED: dict[str, Any] = {
    "CONFIG.md": render_config,
    "MCP_TOOLS.md": render_mcp_tools,
    "MODULE_MAP.md": render_module_map,
}


def regenerate(docs: Path = DOCS, check: bool = False) -> list[str]:
    """Write (or, with *check*, compare) every generated catalog.

    Returns the paths whose on-disk content was (or would be) changed.  An
    empty list means the tree is current.
    """
    changed: list[str] = []
    for name, render in GENERATED.items():
        target = docs / name
        rendered = render()
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == rendered:
            continue
        changed.append(
            str(target.relative_to(REPO)) if target.is_relative_to(REPO) else str(target)
        )
        if not check:
            target.write_text(rendered, encoding="utf-8")
    return changed


def main(argv: list[str] | None = None) -> int:
    """Rewrite the catalogs, or with ``--check`` report the ones out of date."""
    args = list(sys.argv[1:] if argv is None else argv)
    check = "--check" in args
    try:
        changed = regenerate(check=check)
    except ValueError as failure:
        sys.stderr.write(f"{failure}\n")
        return 1
    for path in changed:
        sys.stdout.write(f"{'stale' if check else 'wrote'} {path}\n")
    if check and changed:
        sys.stderr.write("run `.venv/bin/python scripts/gen_docs.py` and commit the result\n")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
